---

- name: Pull Git Repo
  git:
    repo: https://github.com/ConnorWhalen/HeavyNFLDB.git
    dest: /opt/HeavyNFLDB
    force: true

- name: Install pip Requirements
  pip:
    requirements: /opt/HeavyNFLDB/requirements.txt
    virtualenv: /opt/HeavyNFLDB/venv

- name: Copy db file
  copy:
    src: heavy-nfld.db
    dest: /opt/HeavyNFLDB/server/heavy-nfld.db

- name: Copy service file
  template:
    src: templates/webserver.j2
    dest: /etc/systemd/system/heavynfld-webserver.service
  become: true

- name: Reload Webserver
  systemd_service:
    name: heavynfld-webserver
    state: restarted
  become: true
