---

- name: Pull Git Repo
  git:
    repo: https://github.com/ConnorWhalen/HeavyNFLDB.git
    dest: /opt/HeavyNFLDB
    force: true

- name: Install pip Requirements
  pip:
    requirements: /opt/HeavyNFLDB/requirements.txt
    virtualenv: /opt/HeavyNFLDB/venv

- name: Copy db file
  copy:
    src: heavy-nfld.db
    dest: /opt/HeavyNFLDB/server/heavy-nfld.db

  
